/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LayoutMainAuthLayout: typeof import('./src/components/layout/main/AuthLayout.vue')['default']
    LayoutSideBar: typeof import('./src/components/layout/SideBar.vue')['default']
    LayoutSidebarLink: typeof import('./src/components/layout/SidebarLink.vue')['default']
    LayoutTopNavbar: typeof import('./src/components/layout/TopNavbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiAvatarAvatarFallback: typeof import('./src/components/ui/avatar/AvatarFallback.vue')['default']
    UiAvatarAvatarImage: typeof import('./src/components/ui/avatar/AvatarImage.vue')['default']
    UiAvatarBaseAvatar: typeof import('./src/components/ui/avatar/BaseAvatar.vue')['default']
    UiButtonBaseButton: typeof import('./src/components/ui/button/BaseButton.vue')['default']
    UiDataTableDataTable: typeof import('./src/components/ui/data-table/DataTable.vue')['default']
    UiDropdownMenuDropdownMenu: typeof import('./src/components/ui/dropdown-menu/DropdownMenu.vue')['default']
    UiDropdownMenuDropdownMenuCheckboxItem: typeof import('./src/components/ui/dropdown-menu/DropdownMenuCheckboxItem.vue')['default']
    UiDropdownMenuDropdownMenuContent: typeof import('./src/components/ui/dropdown-menu/DropdownMenuContent.vue')['default']
    UiDropdownMenuDropdownMenuGroup: typeof import('./src/components/ui/dropdown-menu/DropdownMenuGroup.vue')['default']
    UiDropdownMenuDropdownMenuItem: typeof import('./src/components/ui/dropdown-menu/DropdownMenuItem.vue')['default']
    UiDropdownMenuDropdownMenuLabel: typeof import('./src/components/ui/dropdown-menu/DropdownMenuLabel.vue')['default']
    UiDropdownMenuDropdownMenuRadioGroup: typeof import('./src/components/ui/dropdown-menu/DropdownMenuRadioGroup.vue')['default']
    UiDropdownMenuDropdownMenuRadioItem: typeof import('./src/components/ui/dropdown-menu/DropdownMenuRadioItem.vue')['default']
    UiDropdownMenuDropdownMenuSeparator: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSeparator.vue')['default']
    UiDropdownMenuDropdownMenuShortcut: typeof import('./src/components/ui/dropdown-menu/DropdownMenuShortcut.vue')['default']
    UiDropdownMenuDropdownMenuSub: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSub.vue')['default']
    UiDropdownMenuDropdownMenuSubContent: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSubContent.vue')['default']
    UiDropdownMenuDropdownMenuSubTrigger: typeof import('./src/components/ui/dropdown-menu/DropdownMenuSubTrigger.vue')['default']
    UiDropdownMenuDropdownMenuTrigger: typeof import('./src/components/ui/dropdown-menu/DropdownMenuTrigger.vue')['default']
    UiInputBaseInput: typeof import('./src/components/ui/input/BaseInput.vue')['default']
    UiTableTable: typeof import('./src/components/ui/table/Table.vue')['default']
    UiTableTableBody: typeof import('./src/components/ui/table/TableBody.vue')['default']
    UiTableTableCaption: typeof import('./src/components/ui/table/TableCaption.vue')['default']
    UiTableTableCell: typeof import('./src/components/ui/table/TableCell.vue')['default']
    UiTableTableEmpty: typeof import('./src/components/ui/table/TableEmpty.vue')['default']
    UiTableTableFooter: typeof import('./src/components/ui/table/TableFooter.vue')['default']
    UiTableTableHead: typeof import('./src/components/ui/table/TableHead.vue')['default']
    UiTableTableHeader: typeof import('./src/components/ui/table/TableHeader.vue')['default']
    UiTableTableRow: typeof import('./src/components/ui/table/TableRow.vue')['default']
  }
}
